### ISSUE TITLE
ライセンスが正しく設定されていない

### ISSUE THREAD

**Issue by Meatwo310** [fixdol/MekanismRadioactive#1]
リポジトリに設定されているライセンスは、[LICENSE.txt](https://github.com/fixdol/MekanismRadioactive/blob/d84cf627a21ff0e383d8ad4843b0da5b22edcc4c/LICENSE.txt)によると(Forgeのテンプレートそのままの)LGPLですが、
jarファイルの[mods.toml](https://github.com/fixdol/MekanismRadioactive/blob/d84cf627a21ff0e383d8ad4843b0da5b22edcc4c/src/main/resources/META-INF/mods.toml)に記載されているライセンスはAll Rights Reservedとなっています。

リポジトリと`mods.toml`の両方に**オープンソースライセンス**を適用することで、
プレイヤーがよりMODを利用しやすくなります。
個人的にはMITライセンスの設定をおすすめしますが、お好きなものを選んでいただくのが良いと思います。

設定の手順ですが、このような流れになると思います
1. `LICENSE.txt`を作り直す(GitHub側のウィザードを利用してください)
2. `mods.toml`の`license`を適切なものに設定する

**Comment by fixdol** [comment]
All Rights Reservedに変更しました。

**Comment by Meatwo310** [comment]
どうやらコミット [1dfaf2d](https://github.com/fixdol/MekanismRadioactive/commit/1dfaf2dc14af59398af770f2f33638434101690f) でLICENSE.txtが競合しているようです。

それより前のコミット [81ebf84](https://github.com/fixdol/MekanismRadioactive/commit/81ebf8467753db6700e52ae77c52a34f8ec2bc7d) では正しくAll Rights Reservedに設定されているため、
前者のコミットをrevertすることで、正しいファイルになるはずです。

(余談ですが、All Rights Reservedを設定することはおすすめしません。)
